# Generated by Django 3.0.7 on 2020-06-25 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSubTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTopics', models.CharField(default='', max_length=200)),
                ('videolink', models.CharField(default='', max_length=500)),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='perfectcourses.Courses')),
                ('courseDetails', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='perfectcourses.CourseDetails')),
            ],
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='perfectcourses.Courses'),
        ),
    ]
